#!/bin/bash

sudo cp ./typematrix /usr/share/X11/xkb/symbols/typematrix
sudo cp ./typematrix_colemak /usr/share/X11/xkb/symbols/typematrix_colemak
sudo cp ./typematrix_softcolemak /usr/share/X11/xkb/symbols/typematrix_softcolemak
sudo cp ./typematrix_halfqwerty /usr/share/X11/xkb/symbols/typematrix_halfqwerty
sudo cp ./mac_halfqwerty /usr/share/X11/xkb/symbols/mac_halfqwerty
sudo cp ./evdev.xml /usr/share/X11/xkb/rules/evdev.xml
setxkbmap -layout typematrix
